[project]
name = "create-slides"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.12"
dependencies = [
    "manim>=0.20.1",
    "python-pptx>=1.0.2",
    "loguru>=0.7.2",
    "rdkit>=2026.3.3",
]

[project.scripts]
create-slide-1 = "create_slides.scripts.create_slide_1:main"
create-all-slides = "create_slides.scripts.create_all_slides:main"

[build-system]
requires = ["hatchling"]
build-backend = "hatchling.build"

[tool.hatch.build.targets.wheel]
packages = ["src/create_slides"]
